services:
  prometheus:
    image: prom/prometheus:latest
    container_name: apire-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - apire-network

  grafana:
    image: grafana/grafana:latest
    container_name: apire-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - apire-network
    depends_on:
      - prometheus

networks:
  apire-network:
    driver: bridge
