apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-checker-web
  labels:
    app: compliance-checker-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance-checker-web
  template:
    metadata:
      labels:
        app: compliance-checker-web
    spec:
      containers:
      - name: web
        image: apire-compliance-checker-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-checker-web
spec:
  selector:
    app: compliance-checker-web
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 80
  type: ClusterIP
